### ISSUE TITLE
Frequently proposes papers that are already in the relevant list

### ISSUE THREAD

**Issue by dtdi** [dtdi/citetool#19]
Frequently proposes papers that are already in the relevant list

_Originally posted by @nieselo in https://github.com/dtdi/citetool/issues/10#issuecomment-758666658_

**Comment by nieselo** [comment]
@dtdi Replacing the code in App.js line309 `(this.onSelectSingle(newList[0]);` with the following code works:
`this.onSelectSingle(newList.filter((paper) => {return paper.inList === LIST_RESULT})[0]);`

**Comment by nieselo** [comment]
@dtdi Has been solved with today's push.
