### ISSUE TITLE
Scopus information (e.g. Abstract link) missing in forward/backward search results

### ISSUE THREAD

**Issue by nieselo** [dtdi/citetool#26]
In forward/backward search, only SemScholar Data is incorporated. Therefore, abstract links are not available for new results.

**Comment by dtdi** [comment]
@nieselo : can you clarify this issue? e.g. attach a screenshot or similar

**Comment by nieselo** [comment]
in "onPaperAction" no SCOPUS API get request is implemented. References are pulled from newPaper.refs, then "loadSemScholarForMany" is called.

Since abstract links are generated in "processSearchResults", and this is not called from "onPaperAction", Abstract links are not available for forward/backward search results.
