### ISSUE TITLE
New search clears relevant list

### ISSUE THREAD

**Issue by bastianstahl** [dtdi/citetool#5]
Running a new search will empty the Relevant list. Either new searches should be possible to find more relevant papers or a warning should appear.

**Comment by dtdi** [comment]
@bastianstahl , @nieselo -> what would be the proposed solution here?

**Comment by bastianstahl** [comment]
Preferred solution would be that the relevant list is kept and you have to clear it actively - @nieselo ?

**Comment by nieselo** [comment]
@dtdi This issue has already been solved, hasn't it?
